const FILE_ID_SOURCE_RECAP = '1JSvQXVhC6InSpULihdoxNGrIjsoZ5V7OplV5CptWc_c';

const DEFAULT_PERIOD_YEAR = 2026;
const DEFAULT_RATE_SUBSIDI = 0.0925;

const MONTH_MAPPED = {
  JANUARI: 1,
  FEBRUARI: 2,
  MARET: 3,
  APRIL: 4,
  MEI: 5,
  JUNI: 6,
  JULI: 7,
  AGUSTUS: 8,
  SEPTEMBER: 9,
  OKTOBER: 10,
  NOVEMBER: 11,
  DESEMBER: 12,
};